plugins:
  - jekyll-redirect-from
  
title: Piyush Singh
position: M. S. Student
affiliation: IIIT Hyderabad
email: piyush.singh (at) research.iiit.ac.in
google_scholar: https://scholar.google.com/citations?hl=en&user=uaxUoc8AAAAJ
github_link: https://github.com/piyush01123
linkedin: https://www.linkedin.com/piyus01123
resume: ./assets/pdf/RESUME.pdf
stackoverflow: https://stackoverflow.com/users/9563006/piyush-singh
avatar: ./assets/img/avatar.png
favicon: ./assets/img/avatar.png
favicon_dark: ./assets/img/avatar.png
description: Pesonal website of Piyush Singh
remote_theme: yaoyao-liu/minimal-light
